version: '3.3'

services:
  postgres-back:
    networks:
      moskalyan:
        aliases:
        - postgres-back
    ports:
    - "15432:5432"
    container_name: postgres-back
    image: postgres:10
    restart: on-failure:3
    environment:cd
      POSTGRES_DB: "back"
      POSTGRES_USER: "back"
      POSTGRES_PASSWORD: "back"

  kafka:
    networks:
      moskalyan:
        aliases:
        - kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
    ports:
    - "9092:9092"
    - "2181:2181"

networks:
  moskalyan:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.21.0.0/25"